# Generated by Django 4.0.3 on 2022-05-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-id'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='actor',
            name='date_of_death',
            field=models.DateField(null=True, verbose_name='Дата смерти'),
        ),
    ]
