# Generated by Django 4.0.3 on 2022-05-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0003_alter_actor_date_of_death'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='url',
            field=models.SlugField(max_length=160, null=True, unique=True),
        ),
    ]
